# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Music Assistant Alexa API add-on
version: "1.0.0"
slug: ma_alexa_api
description: Music Assistant Alexa API add-on
url: "https://github.com/timlaing/music-assistant-alex-api/tree/main/music-assistant-alex-api"
arch:
  - aarch64
  - amd64
init: false
options:
  api_username: "ma-local-alexa-api"
schema:
  ma_hostname: "str"
  api_username: "str"
  api_password: "password?"
  aws_default_region: "str?"
# image: "ghcr.io/timlaing/{arch}-addon-ma-alexa-api"
webui: "[PROTO:option_name]://[HOST]:[PORT:5000]/status"
watchdog: "[PROTO:option_name]://[HOST]:[PORT:5000]/status"
stage: experimental
homeassistant: 2025.12.1
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "The API port"